// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz6K4hpvQlGCp4sO6vl2CIw6jl1lWe0TU',
    appId: '1:283560472557:web:6448fed104d6eb7865c1e4',
    messagingSenderId: '283560472557',
    projectId: 'happychat-f8f34',
    authDomain: 'happychat-f8f34.firebaseapp.com',
    storageBucket: 'happychat-f8f34.firebasestorage.app',
    measurementId: 'G-FXW5MKE292',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUT8WHNQWKult0JXfJLmxbN4r07m2-NE4',
    appId: '1:283560472557:android:7fbb176e167409d465c1e4',
    messagingSenderId: '283560472557',
    projectId: 'happychat-f8f34',
    storageBucket: 'happychat-f8f34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-uzFCivmjJt4LnMyBCgX5lPw-LkgMRo',
    appId: '1:283560472557:ios:58604cae73ee1a8365c1e4',
    messagingSenderId: '283560472557',
    projectId: 'happychat-f8f34',
    storageBucket: 'happychat-f8f34.firebasestorage.app',
    iosBundleId: 'com.example.happyWedz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa-uzFCivmjJt4LnMyBCgX5lPw-LkgMRo',
    appId: '1:283560472557:ios:58604cae73ee1a8365c1e4',
    messagingSenderId: '283560472557',
    projectId: 'happychat-f8f34',
    storageBucket: 'happychat-f8f34.firebasestorage.app',
    iosBundleId: 'com.example.happyWedz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz6K4hpvQlGCp4sO6vl2CIw6jl1lWe0TU',
    appId: '1:283560472557:web:17d27e614e9c5d4d65c1e4',
    messagingSenderId: '283560472557',
    projectId: 'happychat-f8f34',
    authDomain: 'happychat-f8f34.firebaseapp.com',
    storageBucket: 'happychat-f8f34.firebasestorage.app',
    measurementId: 'G-HZPB85981K',
  );

}