// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_BPG8ujwTFK6bKsq__WcMzT8Y6IPgd3I',
    appId: '1:27907630225:web:54c106376e74a06e8f4b30',
    messagingSenderId: '27907630225',
    projectId: 'happy-wedz-1ebe2',
    authDomain: 'happy-wedz-1ebe2.firebaseapp.com',
    storageBucket: 'happy-wedz-1ebe2.firebasestorage.app',
    measurementId: 'G-R95Q6XVGC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbnw_dz8ah5AEwr_dsF1wLIAX4tnAYjDE',
    appId: '1:27907630225:android:e89c6b97aa932afb8f4b30',
    messagingSenderId: '27907630225',
    projectId: 'happy-wedz-1ebe2',
    storageBucket: 'happy-wedz-1ebe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQO-ycCHpvnFhffaRkHN1tAH4O842cSaA',
    appId: '1:27907630225:ios:8e1cc80b6c941e208f4b30',
    messagingSenderId: '27907630225',
    projectId: 'happy-wedz-1ebe2',
    storageBucket: 'happy-wedz-1ebe2.firebasestorage.app',
    androidClientId: '27907630225-u6mct1p7kt2uvv8b3gcsqdhf4dmts8ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyWedz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQO-ycCHpvnFhffaRkHN1tAH4O842cSaA',
    appId: '1:27907630225:ios:8e1cc80b6c941e208f4b30',
    messagingSenderId: '27907630225',
    projectId: 'happy-wedz-1ebe2',
    storageBucket: 'happy-wedz-1ebe2.firebasestorage.app',
    androidClientId: '27907630225-u6mct1p7kt2uvv8b3gcsqdhf4dmts8ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyWedz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_BPG8ujwTFK6bKsq__WcMzT8Y6IPgd3I',
    appId: '1:27907630225:web:e3dbe562cfea8c518f4b30',
    messagingSenderId: '27907630225',
    projectId: 'happy-wedz-1ebe2',
    authDomain: 'happy-wedz-1ebe2.firebaseapp.com',
    storageBucket: 'happy-wedz-1ebe2.firebasestorage.app',
    measurementId: 'G-QNB9L0CERH',
  );
}
